version: '3.8'

networks:
  main:
  logs:
    external: true

services:
  backend:
    build: .\PpServerBot\.
    ports:
      - "127.0.0.1:9501:3001"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS=http://+:3001
      - osuApi__ClientId
      - osuApi__ClientSecret
      - osuApi__CallbackUrl=/verify
      - HuisToken
      - DiscordConfig__Token
      - DiscordConfig__GuildId
      - DiscordConfig__ApplicationChannelId
      - DiscordConfig__VerifiedChannelId
      - DiscordConfig__OnionVerifiedChannelId
      - DiscordConfig__Roles__Onion
      - DiscordConfig__Roles__Verified
    volumes:
      - ./logs:/app/logs
      - ./keys:/root/.aspnet/DataProtection-Keys
    networks:
      - main
      - logs
    restart: unless-stopped
    pull_policy: build
